# Site wide configuration

title:            Oliver Barreto - Lost in IT & Business Translation
description:      My journey Learning and Bringing Ideas to life
locale:           en_US
logo:             site-logo.png
#Change url to your domain. Leave localhost server or blank when working locally.
#url:              http://localhost:4000
url:              http://oliverbarreto.com



# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name:           Oliver Barreto
  avatar:         bio-photo.jpg
  email:          oliver.barreto.online@gmail.com
  disqus_shortname: "oliverbarretosbuildoneideas"
  twitter:        "oliverbarreto"
  facebook:       "oliverbarretorodriguez"
  github:         "oliverbarreto"
  stackexchange:
  linkedin:       "oliverbarreto"
  instagram:      "oliverbarreto"
  flickr:         "oliverbarreto"
  stackexchange: #http://stackoverflow.com/users/123456/username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: "http://plus.google.com/109194913708916482599"
    analytics: UA-46702055-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:

# Links to include in top navigation
# # For external links add external: true
# links:
#   - title: About
#     url: /about
#   - title: Blog
#     url: /blog
#   - title: OneIDeas
#     url: /oneideas
# #  - title: Made Mistakes
# #    url: http://mademistakes.com
# #    external: true

# # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# timezone:    Atlantic/Canary
# future:      true
# pygments:    true



